name: Generate ASCII Workflow

on: push

jobs: 
    build_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Sleep for 30 seconds
              run: sleep 30
    
    test_job2:
        runs-on: ubuntu-latest #different machine from the previous job
        steps:
          - name: Sleep for 10 seconds
            run: sleep 10
            
          - name: Test File Exists
            run: grep -i "dragon" dragon.txt

          - name: Read File
            run: cat dragon.txt
    
    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt
            
            - name: Deploy
              run: echo Deploying ...
            

            
           