name: Use uploads and download artifacts

on: push

jobs: 
    build_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Upload the dragon text file
              uses: actions/upload-artifact@v4.6.2
              with:
                name: dragon-text-file
                path: dragon.txt
    
    test_job2:
        needs: build_job
        runs-on: ubuntu-latest #different machine from the previous job
        steps:
         - name: Download the dragon text file
           uses: actions/download-artifact@v4.3.0
           with:
            name : dragon-text-file
            
         - name: Test File Exists
           run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
        needs: [test_job2]
        runs-on: ubuntu-latest
        steps:
            - name: Download the dragon text file
              uses: actions/download-artifact@v4.3.0
              with:
                name: dragon-text-file
                
            - name: Read File
              run: cat dragon.txt
            
            - name: Deploy
              run: echo Deploying ...
            

            
           